# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-extension-1"
client_id = "d7ddf9c0daba08f052c2823af1e9a364"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "rajib-shop-1.myshopify.com"
